# Generated by Django 4.1.6 on 2025-10-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone',
            new_name='mobile',
        ),
    ]
