# Generated by Django 4.1.6 on 2025-11-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_at',
        ),
    ]
