# Generated by Django 4.1.6 on 2025-11-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_cart_added_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
