# Generated by Django 4.1.6 on 2025-11-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
